# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Codebits by David Medinets
email: david.medinets@gmail.com
description: a personal technical blog.
baseurl: ""
url: "http://medined.github.io"
twitter_username: rubybits
github_username:  medined
timezone: America/New_York
encoding: utf-8

paginate: 1
paginate_path: "/blog/page:num/"

# Build settings
markdown: kramdown
gems: [jekyll-paginate]
